version: '3.1'
services:

  db:
    image: mysql:8.0.36
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: search_cep_db
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/container/mysql

volumes:
  db:
    driver: local
